include: package:pedantic/analysis_options.yaml


linter:
  rules:
    omit_local_variable_types: false
    prefer_const_constructor: true
    avoid_void_async: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

analyzer:
  exclude:
    - 'lib/**.g.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false